/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    cuadratica()
    valores_de_la_funcion()
}

fun cuadratica (){
    val a = 5.0
    val b = -3.0
    val c = 6.0
    if (a === 0.0) {
        println("No se puede poner que a=0 ")
        return
    }

    println("La cuenta quedaria así ${a}x² + ${b}x + $c = y")
}

fun valores_de_la_funcion (){
    val a = 5.0
    val b = -3.0
    val c = 6.0

    for (x in -10..10) {
        val y = a * x * x + b * x + c
        println("f($x) = $y")
    }
}